#!/usr/bin/env python3
"""Render the webhook event catalog into webhooks.md.

The catalog lives in one place in this repo:
plugins/buildbase/knowledge/http-api/webhook-events.json, a vendored copy of
`SYSTEM_EVENTS` from the BuildBase platform (see its `source` block). This
script renders that JSON into the `## Event catalog` section of
knowledge/http-api/webhooks.md between two marker comments, so the prose file
and the machine-readable file cannot drift. validate.py re-renders and compares.

Usage:
  python3 scripts/render-webhook-catalog.py           # rewrite the section
  python3 scripts/render-webhook-catalog.py --check   # exit 1 if it is stale
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTTP_API = os.path.join(ROOT, "plugins", "buildbase", "knowledge", "http-api")
CATALOG = os.path.join(HTTP_API, "webhook-events.json")
TARGET = os.path.join(HTTP_API, "webhooks.md")
START = "<!-- webhook-catalog:start (generated by scripts/render-webhook-catalog.py, do not edit by hand) -->"
END = "<!-- webhook-catalog:end -->"


def load_catalog(path=CATALOG):
    with open(path) as f:
        return json.load(f)


def render(catalog):
    src = catalog["source"]
    lines = [
        START,
        "",
        "All %d event names, vendored from `%s` (`%s`) at commit `%s` on %s. "
        "A name that is not in this list does not exist; never invent one. The "
        "same list is machine-readable in [webhook-events.json](./webhook-events.json)."
        % (catalog["count"], src["path"], src["constant"], src["commit"][:12], src["syncedOn"]),
        "",
    ]
    for cat in catalog["categories"]:
        lines.append("**%s** (`%s.*`)" % (cat["category"], cat["domain"]))
        lines.append("")
        for ev in cat["events"]:
            lines.append("- `%s`" % ev)
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def splice(text, section):
    start = text.find(START)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        raise SystemExit("markers not found in %s" % TARGET)
    return text[:start] + section + text[end + len(END):]


def main():
    catalog = load_catalog()
    section = render(catalog)
    with open(TARGET) as f:
        current = f.read()
    updated = splice(current, section)
    if "--check" in sys.argv:
        if updated != current:
            print("webhooks.md event catalog is stale; run scripts/render-webhook-catalog.py")
            sys.exit(1)
        print("webhooks.md event catalog matches webhook-events.json")
        return
    if updated != current:
        with open(TARGET, "w") as f:
            f.write(updated)
        print("rendered %d events into %s" % (catalog["count"], os.path.relpath(TARGET, ROOT)))
    else:
        print("already up to date")


if __name__ == "__main__":
    main()
